// <copyright file="RewardsErrorCode.cs" company="Microsoft">Copyright (c) Microsoft. All rights reserved.</copyright>
// Sourced these classes from : https://msasg.visualstudio.com/rewards/_git/M.Rewards_Platform?path=/Models/Models/RequestModels.cs&version=GBcontainers&_a=contents

namespace Microsoft.Commerce.Payments.PXService.Accessors.MSRewardsService.DataModel
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "historical")]
    public enum RewardsErrorCode
    {
        // Success
        Success = 0,

        // Generic Errors: 1-1000
        E_VALIDATION_ERROR = 1,
        E_MISSING_REQUEST_DATA = 3,
        E_DATABASE_ERROR = 4,
        E_USER_MAPPING_NOT_FOUND = 5,
        E_USER_NOT_FOUND = 6,
        E_USER_SUSPENDED = 9,
        E_USER_OPTOUT = 10,
        E_UNSUPPORTED_COUNTRY = 11,
        E_UNSUPPORTED_LANGUAGE = 12,
        E_TIMEOUT = 13,
        E_THROTTLED = 14,
        E_API_ACCESS_DENIED = 15,
        E_NOT_FOUND = 16,
        E_EXISTING_OBJECT = 17,
        E_UNAUTHORIZED_REQUEST = 18,
        E_MISSING_HEADER = 19,
        E_USER_CREATION_FAILURE = 20,
        E_GET_USER_FAILURE = 21,
        E_EVENTHUB_MESSAGE_POST_FAILURE = 22,
        E_LINKED_USER_NOT_FOUND = 23,
        E_USER_ALREADY_WAITLISTED = 24,
        E_USER_NOT_WAITLISTED = 25,
        E_USER_INVALID_WAITLIST_STATE = 26,
        E_USER_ALREADY_ELIGIBLE = 27,
        E_USER_NOT_ADULTMSA = 28,
        E_USER_AUTOJOIN_WAITLIST_NOT_ALLOWED = 29,
        E_USER_AUTO_APPROVAL_ERROR = 30,
        E_USER_JARVIS_FORBIDDEN_ERROR = 31,
        E_USER_NOT_FOUND_OR_CREATED = 32,
        E_USER_AGENT_NOT_VALID = 33,

        E_INSUFFICIENT_BALANCE = 2002,
        E_INVALID_SKU = 2003,
        E_ORDER_FAILURE = 2004,
        E_SOLVE_FAILURE = 2005,
        E_CHALLENGE_FAILURE = 2006,
        E_CHALLENGE_FIRST = 2007,
        E_SOLVE_FIRST = 2008,
        E_RISK_REJECT = 2009,
        E_RISK_FAILURE = 2010,
        E_RISK_REVIEW = 2011,
        E_RETRYING_ON_FAILURE = 2012,
        E_AnnualRedemptionLimitExceeded = 2013,
        E_GiftSendLimitExceeded = 2014,
        E_GiftReceiveLimitExceeded = 2015,
        E_GiftReceiveFailure = 2016,
        E_InvalidRequestAmount = 2017,
        E_ExistingPointRequest = 2018,
        E_CANNOT_APPLY_TOKEN = 2019,
        E_TOKEN_PROMO_NOT_FOUND = 2020,
        E_TOKEN_PROMO_NOT_ELIGIBLE = 2021,
        E_EXTERNAL_DEPENDENCY_ERROR = 2022,
        E_REDEMPT_FAILURE = 2023,
        E_REFUND_BALANCE_FAILURE = 2024,
        E_NOT_SUPPORT_CURRENCY = 2025,
        E_INVALID_EMAIL = 2026,
        E_DECRYPTION_ERROR = 2027,
        E_IRIS_FAILURE = 2028,
        E_DISABLED_SKU = 2029,
        E_BOT_REJECT = 2030,
        E_GEO_LOCATION_REJECT = 2031,
        E_FRAUD_REJECT = 2032,
        E_DENIED = 2033,
        E_USER_QUARANTINED = 2034,
        E_CAPTCHA_INVALID_REJECT = 2035,
        E_GEO_LOCATION_CHALLENGE = 2036,
        E_REDEMPTION_WITHOUT_CAPTCHA_TRIGGER = 2037,
        E_REDEMPTION_WITHOUT_CETO = 2038,
        E_REDEMPTION_WITH_EXPIRED_CAPTCHA = 2039,
        E_REDEMPTION_WITH_COPYING_CAPTCHA_COOKIE = 2040,
        E_REDEMPTION_WITH_UNKNOWN_CAPTCHA_ISSUE = 2041,
        E_EXISTING_RISK_REVIEW = 2042,

        E_RESTORE_STREAK_NOT_APPLICABLE = 2100,
        E_RESTORE_STREAK_NOT_APPLICABLE_NO_STREAK_ATTR = 2101,
        E_RESTORE_STREAK_NOT_APPLICABLE_RESTORED_RECENTLY = 2102,
        E_RESTORE_STREAK_NOT_APPLICABLE_NEVER_RESET = 2103,
        E_RESTORE_STREAK_NOT_APPLICABLE_RESET_LONG_TIME_AGO = 2104,
        E_RESTORE_STREAK_NOT_APPLICABLE_RESET_LESS_THAN_CUR = 2105,

        // API: Create Profile. Codes: 3001-4000
        E_NO_USER_DATA = 3001,
        E_EXISTING_USER = 3002,
        E_EXISTING_NON_AUTO_JOIN_USER = 3003,
        E_EXISTING_USER_INVALID_AUTO_JOIN_CONVERSION_REQUEST = 3004,

        E_INVALID_TEST_USER = 4001,

        E_INVALID_PROPERTY_FOR_UPDATE = 5001,
        E_ORDER_EXISTS = 5002,
        E_ORDER_NOT_FOUND = 5003,
        E_INVALID_ORDER_ID = 5004,

        // External Dependency Errors: 6001-7000
        E_ICG_SEND_DATA_FAILURE = 6001,

        // Refer A Friend 7001-8000
        E_REFERRER_NOT_FOUND = 7001,
        E_REFERRER_SEND_EMAIL_EXCEEDED = 7002,
        E_REFERRER_RECEIVE_EMAIL_EXCEEDED = 7003,
        E_REFERRER_OPTOUT_EMAIL = 7004,
        E_REFERRER_SEND_EMAIL_FAILURE = 7005,

        // Give Mode 8001-9000
        E_INVALID_GIVE_ORGANIZATION = 8001,
        E_INVALID_GIVE_REQUEST = 8002,
        E_BENEVITY_SERVICE_SEARCH_FAILURE_TOP_100 = 8003,
        E_INVALID_GIVE_SEARCH_REQUEST = 8004,
        E_BENEVITY_SERVICE_SEARCH_COUNTRY_RESPONSE_MISMATCH = 8005,

        // Auto Redeem 9001-10000
        E_ALREADY_SUBSCRIBED_TO_SKU = 9001,
        E_MAX_SUBSCRIPTIONS_EXCEEDED = 9002,
        E_INVALID_UNSUBSCRIPTION = 9003,
        E_AUTOREDEEM_FAILURE = 9004,
        E_INVALID_RISK_CONTEXT = 9005,
        E_RISK_CHECK_FAILURE = 9006,
        E_INVALID_PAYMENT_TYPE = 9007,
        E_INVALID_SUBSCRIPTION = 9008,

        // Trial User Association 10001-11000
        E_USER_ALREADY_ASSOCIATED = 10001,
        E_TRIAL_ASSOCIATE_INTERNAL_ERROR = 10002,
        E_USER_NON_TRIAL_ACCOUNT = 10003,
        E_TRIAL_NOT_PRESENT = 10004,
        E_TRIAL_EXPIRED = 10005, // returned when user's trial account was closed due to 30d expiration

        // Rebate 11001-11999
        E_EVENT_NOT_FOUND_IN_AFFILIATE = 11002,
        E_EVENT_CANNOT_BE_REPLAYED = 11003,
        E_REBATES_ENROLLMENT_FAILED = 11004,
        E_REBATES_ERROR_RETRIEVING_AUTH_TOKEN = 11005,
        E_REBATES_ERROR_LINKING_CARD = 11006,
        E_REBATES_ERROR_RETRIEVING_CARD_DETAILS = 11007,
        E_REBATES_ERROR_DELETING_CARD_DETAILS = 11008,
        E_REBATES_ERROR_LINKING_OFFER = 11009,
        E_REBATES_ERROR_RETRIEVING_LINKED_OFFERS = 11010,
        E_REBATES_ERROR_RETRIEVING_VENUE_DETAILS = 11011,
        E_REBATES_ERROR_CONVERTING_VENUE_DETAILS = 11012,
        E_REBATES_ERROR_RETRIEVING_VENUES = 11013,
        E_REBATES_ERROR_CONVERTING_VENUES = 11014,
        E_REBATES_ERROR_RETRIEVING_TRANSACTIONS = 11015,
        E_REBATES_ERROR_TRANSACTION_CONVERSION = 11016,
        E_REBATES_ERROR_CAMPAIGN_ID_NOT_ENROLLED = 11017,
        E_REBATES_ERROR_UPSIDE_GET_USER_ID = 11018,
        E_REBATES_ERROR_UPSIDE_TRX_PROCESS = 11019,
        E_REBATES_ERROR_PUID_RESOLVE_PAYLOAD = 11020,
        E_REBATES_ERROR_INVALID_IDENTIFIER_TYPE = 11021,
        E_REBATES_ERROR_SUBSTRATE_CALL = 11022,
        E_REBATES_ERROR_ENROLLBONUS_EARNED = 11023,

        // Third party 12000-13000
        E_THIRDPARTY_REPORT_FAILURE = 12000,
        E_THIRDPARTY_SUBSCRIPTION_FAILURE = 12001,
        E_THIRDPARTY_SUBSCRIPTION_UNSUPPORTED = 12002,
        E_THIRDPARTY_ALREADY_SUBSCRIBED = 12003,
        E_THIRDPARTY_INVALID_UNSUBSCRIPTION = 12004,
        E_THIRDPARTY_CREATE_FAILURE = 12005,
        E_THIRDPARTY_PLACEORDER_FAILURE = 12006,
        E_THIRDPARTY_GET_FAILURE = 12007,
        E_THIRDPARTY_WILDFIRE_CALLBACK_FAILURE = 12008,
        E_THIRDPARTY_INVALID_USER_ID = 12011,

        E_CHECK_FEATURE_FAILURE = 12009,

        // Variable Redemption
        E_INVALID_VARIABLE_REDEMPTION_REQUEST = 12010,

        // PX Deserialization Error
        E_REWARDS_GENERIC_ERROR = 13001,
    }
}