parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

- name: 'buildType'
  displayName: 'Pipeline build type' # Official|PullRequest|Buddy
  type: string
  default: ""

- name: 'sign'
  displayName: 'CodeSign files'
  type: boolean
  default: true

stages:
- stage: build
  jobs:
  - job: main
    pool:
      type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs
    variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
      ob_outputDirectory: '$(Build.SourcesDirectory)\Drop' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
      ob_sdl_binskim_break: true # https://aka.ms/obpipelines/sdl
      ob_sdl_baseline_baselineFile: $(Build.SourcesDirectory)\.gdn\build.gdnbaselines
      # ob_sdl_suppression_suppressionFile: $(Build.SourcesDirectory)\.gdn\build.gdnsuppress
    steps:
      - task: onebranch.pipeline.version@1 # generates automatic version. For other versioning options check https://aka.ms/obpipelines/versioning
        displayName: 'Setup BuildNumber'
        inputs:
          system: 'RevisionCounter'
          major: '1'
          minor: '0'
          exclude_commit: true
      - task: CmdLine@2
        displayName: 'Output build version for output'
        inputs:
          script: |
            if not exist %OB_OUTPUTDIRECTORY% mkdir %OB_OUTPUTDIRECTORY%
            if not exist %OB_OUTPUTDIRECTORY%\Package mkdir %OB_OUTPUTDIRECTORY%\Package
            if not exist %OB_OUTPUTDIRECTORY%\Package\Ev2 mkdir %OB_OUTPUTDIRECTORY%\Package\Ev2
            echo %BUILD_BUILDNUMBER% > %OB_OUTPUTDIRECTORY%\Package\Ev2\BuildVer.txt
            echo %BUILD_BUILDNUMBER%
      - task: Powershell@2
        displayName: 'Update build version in web.config file'
        inputs:
          targetType: 'inline'
          script: |
            $filePath = "$(Build.SourcesDirectory)\private\Payments\PXService\Web.config"
            (Get-Content $filePath).Replace("_build_version_","$(Build.BuildNumber)") | Set-Content $filePath
      # Restore
      - task: PowerShell@2
        displayName: "Restore"
        inputs:
          targetType: "filePath" # Optional. Options: filePath, inline
          filePath: '$(Build.SourcesDirectory)\.build\oneBranch\oneBranch_restore.ps1'
          errorActionPreference: "stop" # Optional. Options: stop, continue, silentlyContinue
          workingDirectory: "$(Build.SourcesDirectory)" # Optional
      # Build
      - task: PowerShell@2
        displayName: "Build"
        inputs:
          targetType: "filePath" # Optional. Options: filePath, inline
          filePath: '$(Build.SourcesDirectory)\.build\oneBranch\oneBranch_build.ps1'
          errorActionPreference: "stop" # Optional. Options: stop, continue, silentlyContinue
          workingDirectory: "$(Build.SourcesDirectory)" # Optional      
      #Run CITs
      - task: PowerShell@2
        displayName: "Run CITs"
        inputs:
         targetType: "filePath" # Optional. Options: filePath, inline
         filePath: '$(Build.SourcesDirectory)\.build\oneBranch\oneBranch_test.ps1'
         errorActionPreference: "stop" # Optional. Options: stop, continue, silentlyContinue
         workingDirectory: '$(ob_outputDirectory)' # Optional
      # Publish Test Results
      - task: PublishTestResults@2
        displayName: "Publish Test Results"
        inputs:
          testResultsFormat: "VSTest" # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: '$(ob_outputDirectory)\Debug\TestResults\**\*.trx'
          searchFolder: '$(ob_outputDirectory)\Debug\TestResults' # Optional
          failTaskOnFailedTests: true # Optional
          testRunTitle: "PXService CIT" # Optional
          publishRunAttachments: true # Optional
      # Copy ev2 folder
      - task: CopyFiles@2
        displayName: "Copy Ev2 folder to Package folder"
        condition: ${{in(parameters.buildType, 'Official', 'Buddy')}}
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)\private\Payments\Deployment.PME'
          Contents: '**'
          TargetFolder: '$(ob_outputDirectory)\Package\Ev2'      
      # Sign
      - task: onebranch.pipeline.signing@1
        displayName: "Sign Output"
        condition: ${{ parameters.sign }}
        inputs:
          command: "sign"
          signing_profile: "internal_azure_service"
          signing_environment: "azure-ado"
          files_to_sign: "**/*.exe;**/*.dll;**/*.ps1;**/*.psm1;**/*.js;**/*.zip"
          search_root: '$(ob_outputDirectory)'
      # Package
      - task: PowerShell@2
        displayName: "Package"
        condition: ${{in(parameters.buildType, 'Official', 'Buddy')}}
        inputs:
          targetType: "filePath" # Optional. Options: filePath, inline
          filePath: '$(Build.SourcesDirectory)\.build\oneBranch\oneBranch_package.ps1'
          errorActionPreference: "stop" # Optional. Options: stop, continue, silentlyContinue
          workingDirectory: '$(ob_outputDirectory)' # Optional