#################################################################################
#                      OneBranch Pipelines - PR Build                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none # https://aka.ms/obpipelines/triggers

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)\out

  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2019/vse2019:latest' # Docker image which is used to build the project https://aka.ms/obpipelines/containers

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    # disable all sdl toolset as they not required for LocBuild
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        enabled: false
      policheck:
        enabled: false
      cg:
        failOnAlert: false
      credscan:
        enabled: false
      armory:
        enabled: false
      eslint:
        enabled: false
      sdtReport:
        enabled: false
      publishLogs:
        enabled: false
      binskim:
        enabled: false
      csrf:
        enabled: false
      bandit:
        enabled: false
      apiscan:
        enabled: false

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs        
        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: '$(OUTPUTROOT)' # this directory is uploaded to pipeline artifacts. More info at https://aka.ms/obpipelines/artifacts
          ob_artifactBaseName: drop

        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              New-Item -Path "$(OUTPUTROOT)" -Force -ItemType Directory
        - task: OneLocBuild@3
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          inputs:
            locProj: 'Localize/LocProject.json'
            outDir: '$(OUTPUTROOT)'
            isCreatePrSelected: true
            isShouldReusePrSelected: true
            isAutoCompletePrSelected: false # Bypass checks to complete the PR automatically.
            isSetAutoCompletePrSelected: true # Set the pull request to automatically complete when all requirements are met.
            prSourceBranchPrefix: 'locfiles'
            dependencyPackageSource: 'https://microsoft.pkgs.visualstudio.com/_packaging/LocTools/nuget/v3/index.json'
            packageSourceAuth: 'patAuth'
        # SBOM Generator
        - task: ManifestGeneratorTask@0
          displayName: 'SBOM Generation Task'
          inputs:
            BuildDropPath: '$(OUTPUTROOT)'