
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.13.0.0
//   Input filename:  BaseEvents.bond
//   Output filename: BaseEvents_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Commerce.Tracing.Sll
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class ServerMessage
        : global::Microsoft.Telemetry.Base
    {
        public string ServiceName { get; set; }

        public string CorrelationId { get; set; }

        public string TrackingGuid { get; set; }

        public string Message { get; set; }

        public ServerMessage()
            : this("Microsoft.Commerce.Tracing.Sll.ServerMessage", "ServerMessage")
        {}

        protected ServerMessage(string fullName, string name)
        {
            ServiceName = "";
            CorrelationId = "";
            TrackingGuid = "";
            Message = "";
        }
    }
} // Microsoft.Commerce.Tracing.Sll
