
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.13.0.0
//   Input filename:  PaymentsEvents.bond
//   Output filename: PaymentsEvents_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Commerce.Tracing.Sll
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class OperationDetails
        : global::Microsoft.Telemetry.Data<global::Ms.Qos.IncomingServiceRequest>
    {
        public string ServiceName { get; set; }

        public string RequestTraceId { get; set; }

        public string ServerTraceId { get; set; }

        public string RequestHeader { get; set; }

        public string ResponseHeader { get; set; }

        public string RequestDetails { get; set; }

        public string ResponseDetails { get; set; }

        public string Message { get; set; }

        public string component { get; set; }

        public string scenarioId { get; set; }

        public string Thumbprint { get; set; }

        public OperationDetails()
            : this("Microsoft.Commerce.Tracing.Sll.OperationDetails", "OperationDetails")
        {}

        protected OperationDetails(string fullName, string name)
        {
            ServiceName = "";
            RequestTraceId = "";
            ServerTraceId = "";
            RequestHeader = "";
            ResponseHeader = "";
            RequestDetails = "";
            ResponseDetails = "";
            Message = "";
            component = "";
            scenarioId = "";
            Thumbprint = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class ClientOperationDetails
        : global::Microsoft.Telemetry.Data<global::Ms.Qos.OutgoingServiceRequest>
    {
        public string ServiceName { get; set; }

        public string RequestTraceId { get; set; }

        public string ServerTraceId { get; set; }

        public string RequestHeader { get; set; }

        public string ResponseHeader { get; set; }

        public string RequestDetails { get; set; }

        public string ResponseDetails { get; set; }

        public string Message { get; set; }

        public ClientOperationDetails()
            : this("Microsoft.Commerce.Tracing.Sll.ClientOperationDetails", "ClientOperationDetails")
        {}

        protected ClientOperationDetails(string fullName, string name)
        {
            ServiceName = "";
            RequestTraceId = "";
            ServerTraceId = "";
            RequestHeader = "";
            ResponseHeader = "";
            RequestDetails = "";
            ResponseDetails = "";
            Message = "";
        }
    }
} // Microsoft.Commerce.Tracing.Sll
