
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.13.0.0
//   Input filename:  PXServiceEvents.bond
//   Output filename: PXServiceEvents_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Commerce.Tracing.Sll
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServiceIncomingOperation
        : global::Microsoft.Telemetry.Data<global::Ms.Qos.IncomingServiceRequest>
    {
        public string ServiceName { get; set; }

        public string RequestTraceId { get; set; }

        public string ServerTraceId { get; set; }

        public string AccountId { get; set; }

        public string InstrumentId { get; set; }

        public string PaymentMethodFamily { get; set; }

        public string PaymentMethodType { get; set; }

        public string Country { get; set; }

        public string ErrorCode { get; set; }

        public string ErrorMessage { get; set; }

        public string RequestHeader { get; set; }

        public string ResponseHeader { get; set; }

        public string RequestDetails { get; set; }

        public string ResponseDetails { get; set; }

        public string Message { get; set; }

        public string StartTime { get; set; }

        public bool IsTest { get; set; }

        public string AuthenticationInfo { get; set; }

        public string Partner { get; set; }

        public string PidlOperation { get; set; }

        public string AvsSuggest { get; set; }

        public PXServiceIncomingOperation()
            : this("Microsoft.Commerce.Tracing.Sll.PXServiceIncomingOperation", "PXServiceIncomingOperation")
        {}

        protected PXServiceIncomingOperation(string fullName, string name)
        {
            ServiceName = "";
            RequestTraceId = "";
            ServerTraceId = "";
            AccountId = "";
            InstrumentId = "";
            PaymentMethodFamily = "";
            PaymentMethodType = "";
            Country = "";
            ErrorCode = "";
            ErrorMessage = "";
            RequestHeader = "";
            ResponseHeader = "";
            RequestDetails = "";
            ResponseDetails = "";
            Message = "";
            StartTime = "";
            AuthenticationInfo = "";
            Partner = "";
            PidlOperation = "";
            AvsSuggest = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServiceOutgoingOperation
        : global::Microsoft.Telemetry.Data<global::Ms.Qos.OutgoingServiceRequest>
    {
        public string ServiceName { get; set; }

        public string RequestTraceId { get; set; }

        public string RequestHeader { get; set; }

        public string ResponseHeader { get; set; }

        public string RequestDetails { get; set; }

        public string ResponseDetails { get; set; }

        public string Message { get; set; }

        public string StartTime { get; set; }

        public string CertInfo { get; set; }

        public string ServicePointData { get; set; }

        public PXServiceOutgoingOperation()
            : this("Microsoft.Commerce.Tracing.Sll.PXServiceOutgoingOperation", "PXServiceOutgoingOperation")
        {}

        protected PXServiceOutgoingOperation(string fullName, string name)
        {
            ServiceName = "";
            RequestTraceId = "";
            RequestHeader = "";
            ResponseHeader = "";
            RequestDetails = "";
            ResponseDetails = "";
            Message = "";
            StartTime = "";
            CertInfo = "";
            ServicePointData = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServicePIAddedOnOffer
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public string serviceName { get; set; }

        public string requestTraceId { get; set; }

        public string paymentInstrumentId { get; set; }

        public string paymentMethodFamily { get; set; }

        public string paymentMethodType { get; set; }

        public string partner { get; set; }

        public string country { get; set; }

        public string offerId { get; set; }

        public string puid { get; set; }

        public PXServicePIAddedOnOffer()
            : this("Microsoft.Commerce.Tracing.Sll.PXServicePIAddedOnOffer", "PXServicePIAddedOnOffer")
        {}

        protected PXServicePIAddedOnOffer(string fullName, string name)
        {
            serviceName = "";
            requestTraceId = "";
            paymentInstrumentId = "";
            paymentMethodFamily = "";
            paymentMethodType = "";
            partner = "";
            country = "";
            offerId = "";
            puid = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServiceOperationTrace
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public string OperationName { get; set; }

        public string AccountId { get; set; }

        public string CorrelationId { get; set; }

        public string SessionId { get; set; }

        public string Message { get; set; }

        public PXServiceOperationTrace()
            : this("Microsoft.Commerce.Tracing.Sll.PXServiceOperationTrace", "PXServiceOperationTrace")
        {}

        protected PXServiceOperationTrace(string fullName, string name)
        {
            OperationName = "";
            AccountId = "";
            CorrelationId = "";
            SessionId = "";
            Message = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServiceOperationFault
        : PXServiceOperationTrace
    {
        public string Target { get; set; }

        public string Details { get; set; }

        public string StackTrace { get; set; }

        public PXServiceOperationFault()
            : this("Microsoft.Commerce.Tracing.Sll.PXServiceOperationFault", "PXServiceOperationFault")
        {}

        protected PXServiceOperationFault(string fullName, string name)
        {
            Target = "";
            Details = "";
            StackTrace = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServiceIngestionMessage
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public string ServiceName { get; set; }

        public string CorrelationId { get; set; }

        public string JobName { get; set; }

        public string SubJobName { get; set; }

        public string Message { get; set; }

        public long LatencyMs { get; set; }

        public string Target1 { get; set; }

        public string Target2 { get; set; }

        public string Target3 { get; set; }

        public PXServiceIngestionMessage()
            : this("Microsoft.Commerce.Tracing.Sll.PXServiceIngestionMessage", "PXServiceIngestionMessage")
        {}

        protected PXServiceIngestionMessage(string fullName, string name)
        {
            ServiceName = "";
            CorrelationId = "";
            JobName = "";
            SubJobName = "";
            Message = "";
            Target1 = "";
            Target2 = "";
            Target3 = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServiceIntegrationError
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public string ServiceName { get; set; }

        public string RequestTraceId { get; set; }

        public string ServerTraceId { get; set; }

        public string IntegrationErrorCode { get; set; }

        public string Message { get; set; }

        public PXServiceIntegrationError()
            : this("Microsoft.Commerce.Tracing.Sll.PXServiceIntegrationError", "PXServiceIntegrationError")
        {}

        protected PXServiceIntegrationError(string fullName, string name)
        {
            ServiceName = "";
            RequestTraceId = "";
            ServerTraceId = "";
            IntegrationErrorCode = "";
            Message = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class PXServiceTraceException
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public string ServiceName { get; set; }

        public string RequestTraceId { get; set; }

        public string StatusCode { get; set; }

        public string Exception { get; set; }

        public PXServiceTraceException()
            : this("Microsoft.Commerce.Tracing.Sll.PXServiceTraceException", "PXServiceTraceException")
        {}

        protected PXServiceTraceException(string fullName, string name)
        {
            ServiceName = "";
            RequestTraceId = "";
            StatusCode = "";
            Exception = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class MISETokenValidationResult
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public bool Success { get; set; }

        public long Latency { get; set; }

        public string CV { get; set; }

        public string ApplicationId { get; set; }

        public string Exception { get; set; }

        public string AuthenticationErrorCode { get; set; }

        public string Message { get; set; }

        public string CloudInstance { get; set; }

        public MISETokenValidationResult()
            : this("Microsoft.Commerce.Tracing.Sll.MISETokenValidationResult", "MISETokenValidationResult")
        {}

        protected MISETokenValidationResult(string fullName, string name)
        {
            CV = "";
            ApplicationId = "";
            Exception = "";
            AuthenticationErrorCode = "";
            Message = "";
            CloudInstance = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class TokenGenerationResult
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public bool Success { get; set; }

        public string Resource { get; set; }

        public string ClientID { get; set; }

        public long Latency { get; set; }

        public string CV { get; set; }

        public string Exception { get; set; }

        public string ExpiresOn { get; set; }

        public TokenGenerationResult()
            : this("Microsoft.Commerce.Tracing.Sll.TokenGenerationResult", "TokenGenerationResult")
        {}

        protected TokenGenerationResult(string fullName, string name)
        {
            Resource = "";
            ClientID = "";
            CV = "";
            Exception = "";
            ExpiresOn = "";
        }
    }
} // Microsoft.Commerce.Tracing.Sll
