
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.13.0.0
//   Input filename:  ReconEvents.bond
//   Output filename: ReconEvents_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Commerce.Tracing.Sll
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.13.0.0")]
    public partial class MetricsDetails
        : global::Microsoft.Telemetry.Data<global::Microsoft.Telemetry.Base>
    {
        public string ServiceName { get; set; }

        public string MetricsName { get; set; }

        public string Status { get; set; }

        public string Timestamp { get; set; }

        public double Quantity { get; set; }

        public string Description { get; set; }

        public string Message { get; set; }

        public string Provider { get; set; }

        public string MerchantId { get; set; }

        public string Currency { get; set; }

        public string IngestedFileName { get; set; }

        public string Version { get; set; }

        public string AdditionalData { get; set; }

        public MetricsDetails()
            : this("Microsoft.Commerce.Tracing.Sll.MetricsDetails", "MetricsDetails")
        {}

        protected MetricsDetails(string fullName, string name)
        {
            ServiceName = "";
            MetricsName = "";
            Status = "";
            Timestamp = "";
            Description = "";
            Message = "";
            Provider = "";
            MerchantId = "";
            Currency = "";
            IngestedFileName = "";
            Version = "";
            AdditionalData = "";
        }
    }
} // Microsoft.Commerce.Tracing.Sll
