// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Commerce.Payments.PXCommon
{
    using Microsoft.Commerce.Payments.Common;
    using Microsoft.Commerce.Payments.Common.Web;
    using Newtonsoft.Json;

    public partial class MicrosoftMarketplaceServicesPurchaseServiceContractsV7ClientContextV7
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftMarketplaceServicesPurchaseServiceContractsV7ClientContextV7
        /// class.
        /// </summary>
        public MicrosoftMarketplaceServicesPurchaseServiceContractsV7ClientContextV7()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftMarketplaceServicesPurchaseServiceContractsV7ClientContextV7
        /// class.
        /// </summary>
        /// <param name="client">Gets or sets the client making the
        /// request.</param>
        /// <param name="deviceFamily">Gets or sets the device family from
        /// which purchase is made.
        /// This field is used for BI logging and tracking</param>
        /// <param name="deviceId">Gets or sets the device Id from which
        /// purchase is made.
        /// This can be null in scenarios where deviceId is not known.
        /// May only be specified by trusted partners (via client cert
        /// auth).</param>
        /// <param name="deviceType">Gets or sets the device type from which
        /// purchase is made.
        /// This can be null when deviceId is null.</param>
        /// <param name="role">Gets or sets the role initiating the call
        /// This can be null when agent is is null or is the caller itself.
        /// May only be specified by trusted partners (via client cert auth).
        /// Possible values include User, Css, and System</param>
        /// <param name="roleOverride">Gets or sets whether risk policy check
        /// is necessary. MST will pass the value as "Exempt".
        /// Only authorized partners will be able to use this property. For
        /// others this value will be ignored</param>
        public MicrosoftMarketplaceServicesPurchaseServiceContractsV7ClientContextV7(string client, string deviceFamily = default(string), string deviceId = default(string), string deviceType = default(string), string role = default(string), string roleOverride = default(string))
        {
            Client = client;
            DeviceFamily = deviceFamily;
            DeviceId = deviceId;
            DeviceType = deviceType;
            Role = role;
            RoleOverride = roleOverride;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the client making the request.
        /// </summary>
        [JsonProperty(PropertyName = "client")]
        public string Client { get; set; }

        /// <summary>
        /// Gets or sets the device family from which purchase is made.
        /// This field is used for BI logging and tracking
        /// </summary>
        [JsonProperty(PropertyName = "deviceFamily")]
        public string DeviceFamily { get; set; }

        /// <summary>
        /// Gets or sets the device Id from which purchase is made.
        /// This can be null in scenarios where deviceId is not known.
        /// May only be specified by trusted partners (via client cert auth).
        /// </summary>
        [JsonProperty(PropertyName = "deviceId")]
        public string DeviceId { get; set; }

        /// <summary>
        /// Gets or sets the device type from which purchase is made.
        /// This can be null when deviceId is null.
        /// </summary>
        [JsonProperty(PropertyName = "deviceType")]
        public string DeviceType { get; set; }

        /// <summary>
        /// Gets or sets the role initiating the call
        /// This can be null when agent is is null or is the caller itself.
        /// May only be specified by trusted partners (via client cert auth).
        /// Possible values include User, Css, and System
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public string Role { get; set; }

        /// <summary>
        /// Gets or sets whether risk policy check is necessary. MST will pass
        /// the value as "Exempt".
        /// Only authorized partners will be able to use this property. For
        /// others this value will be ignored
        /// </summary>
        [JsonProperty(PropertyName = "roleOverride")]
        public string RoleOverride { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Client == null)
            {
                throw new ValidationException(ErrorCode.CannotBeNull, "Client");
            }
        }
    }
}
