// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Commerce.Payments.PXCommon
{
    using Microsoft.Commerce.Payments.Common;
    using Microsoft.Commerce.Payments.Common.Web;
    using Newtonsoft.Json;

    public partial class MicrosoftMarketplaceServicesPurchaseServiceContractsV7IdentityV7
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftMarketplaceServicesPurchaseServiceContractsV7IdentityV7
        /// class.
        /// </summary>
        public MicrosoftMarketplaceServicesPurchaseServiceContractsV7IdentityV7()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftMarketplaceServicesPurchaseServiceContractsV7IdentityV7
        /// class.
        /// </summary>
        /// <param name="identityType">Gets or sets the identity type.</param>
        /// <param name="identityValue">Gets or sets the identity
        /// value.</param>
        public MicrosoftMarketplaceServicesPurchaseServiceContractsV7IdentityV7(string identityType, string identityValue, MicrosoftMarketplaceServicesPurchaseServiceContractsV7OrganizationIdentityV7 organization = default(MicrosoftMarketplaceServicesPurchaseServiceContractsV7OrganizationIdentityV7))
        {
            IdentityType = identityType;
            IdentityValue = identityValue;
            Organization = organization;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the identity type.
        /// </summary>
        [JsonProperty(PropertyName = "identityType")]
        public string IdentityType { get; set; }

        /// <summary>
        /// Gets or sets the identity value.
        /// </summary>
        [JsonProperty(PropertyName = "identityValue")]
        public string IdentityValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "organization")]
        public MicrosoftMarketplaceServicesPurchaseServiceContractsV7OrganizationIdentityV7 Organization { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (IdentityType == null)
            {
                throw new ValidationException(ErrorCode.CannotBeNull, "IdentityType");
            }
            if (IdentityValue == null)
            {
                throw new ValidationException(ErrorCode.CannotBeNull, "IdentityValue");
            }
            if (Organization != null)
            {
                Organization.Validate();
            }
        }
    }
}
